### ISSUE TITLE
Object Reference Error

### ISSUE THREAD

**Issue by mank-kmbs** [LoremFooBar/sarif-bitbucket-pipe#1]
I was recently setting up this pipe to process a sarif file generated by JetBrains InspectCode.  I'm getting an object reference error:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at LoremFooBar.SarifBitbucketPipe.AnnotationsCreator.CreateAnnotationsFromSarifResults(IReadOnlyList`1 results)+MoveNext() in /source/AnnotationsCreator.cs:line 48
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LoremFooBar.SarifBitbucketPipe.PipeRunner.RunPipe() in /source/PipeRunner.cs:line 60
   at Program.<Main>$(String[] args) in /source/Program.cs:line 3
   at Program.<Main>(String[] args)
```

   I did some digging and found that it appears the Rule that gets put into the sarif file is missing the "shortDescription", so the code on line 54 "string.IsNullOrWhiteSpace(rule.ShortDescription.Text)" errors because the "rule.ShortDescription" object is null.
   
   Here is the rule that the JetBrains Inspect dumped out

```json   
{
  "id": "ConditionalAccessQualifierIsNonNullableAccordingToAPIContract",
  "fullDescription": {
    "text": "Conditional access qualifier expression is not null according to nullable reference types' annotations"
  },
  "defaultConfiguration": {
    "level": "warning"
  },
  "relationships": [
    {
      "target": {
        "id": "CSHARP.CodeRedundancy",
        "toolComponent": {
          "name": "InspectCode"
        }
      },
      "kinds": [
        "superset"
      ]
    }
  ]
}

**Comment by LoremFooBar** [comment]
Fixed in `v0.1.1`. 
Thanks you for taking the time to report, hope you find this pipe useful :)
